### ISSUE TITLE
UIAlertController "unrecognized selector sent to instance"

### ISSUE THREAD

**Issue by nico-val** [StylingKit/StylingKit#44]
Hi. My app is crashing with "unrecognized selector sent to instance" when trying to present a UIAlertController on a device (this works fine in simulator). Is there any way I can solve this? Please, I need a hand, since my app is crashing on production.

**Comment by nico-val** [comment]
If I present an empty UIAlertController (without any buttons or text fields), it works fine.
When adding buttons or text fields, my app crashes with the following message:

<Error>: -[_UIAlertControllerCollectionViewCell setPxStyleParent:]: unrecognized selector sent to instance 0x17982a60

**Comment by anton-matosov** [comment]
This might be related to the way you define styles for the collection view and cells. 
If you have element selectors (`collection-view`) try to change them to class selectors and assign class to all collection views in your app.

Can you please try to re-create the issue in the minimal test project and upload it to github?
I am using this framework in 2 apps in prod and don't have issue like that, so I really need a sample app to reproduce and investigate the issue.

**Comment by anton-matosov** [comment]
Closing the issue due to inactivity.
If issue still exists please feel free to provide more information and reopen or create new ticket.
