### ISSUE TITLE
Dependency "StylingKit" has no shared framework schemes

### ISSUE THREAD

**Issue by kunal30xi** [StylingKit/StylingKit#48]
We are attempting to evaluate StylingKit and ran into an issue after adding StylingKit as a dependency to our Cartfile. 

Executing `carthage update`yields the following error:

**\* Checking out CocoaLumberjack at "2.3.0"
**\* Checking out StylingKit at "0.4.0"
**\* xcodebuild output can be found in /var/folders/pp/lqwtjjl95rdfpxfpm_7210xc0000gn/T/carthage-xcodebuild.t8zTja.log
**\* Building scheme "CocoaLumberjack" in Lumberjack.xcworkspace
**\* Skipped building StylingKit due to the error:
Dependency "StylingKit" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/StylingKit/StylingKit/issues/new

Any help in resolving this would be greatly appreciated.

Thanks!

**Comment by anton-matosov** [comment]
Thanks for reporting the issue. I will fix it shortly.

**Comment by anton-matosov** [comment]
I have fixed the issue. Please try it out now.

**Comment by kunal30xi** [comment]
👍
