### ISSUE TITLE
iOS10 Beta 4, iOS11 beta 1,2 - App crashes on launch (naming conflict with PhotosUICore.framework)

### ISSUE THREAD

**Issue by iellis** [StylingKit/StylingKit#49]
In testing an app for the impending ios10 launch, we found that the app crashes on lunch when StylingKit is installed. If I remove the pod, it runs fine (without styling). This occurs even before applicationDidFinishLaunching is called. The app works with styling on iOS 9.

**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIStatusBarForegroundStyleAttributes setContentMode:]: unrecognized selector sent to instance 0x14fcae20'

I searched the StylingKit/Freestyle source for any references to UIStatusBarForegroundStyleAttributes and found none.

Do you have any ideas or guidance that might help? Thanks!

Other possibly related information:

The reason I switched to StylingKit from PixateFreestyle is because the app was crashing in this scenario on [window makeKeyAndVisible] with even less information.

I'm seeing these warnings on app start before the crash.
objc[717]: Class PXPath is implemented in both /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore (0x3901e65c) and /var/containers/Bundle/Application/105E68FD-A40B-4E2D-8394-A589DF897568.... One of the two will be used. Which one is undefined.
objc[717]: Class PXShapeView is implemented in both /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore (0x3901d4a0) and /var/containers/Bundle/Application/105E68FD-A40B-4E2D-8394-A589DF897568/...(0xf57dcc). One of the two will be used. Which one is undefined.
objc[717]: Class PXUIButton is implemented in both /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore (0x3901fcb4) and /var/containers/Bundle/Application/105E68FD-A40B-4E2D-8394-A589DF897568/...(0xf582cc). One of the two will be used. Which one is undefined.
objc[717]: Class PXUIImageView is implemented in both /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore (0x3901f764) and /var/containers/Bundle/Application/105E68FD-A40B-4E2D-8394-A589DF897568/... (0xf583e4). One of the two will be used. Which one is undefined.
objc[717]: Class PXUILabel is implemented in both /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore (0x39020ca4) and /var/containers/Bundle/Application/105E68FD-A40B-4E2D-8394-A589DF897568/... (0xf5840c). One of the two will be used. Which one is undefined.

**Comment by anton-matosov** [comment]
I didn't have a chance to try out StylingKit on iOS 10 yet.
It seems to be dynamic subclassing issue. All UIView derived classes are dynamicaly subclassed at runtime (UIStatusBarForegroundStyleAttributes doesn't seem to be the right one based on this https://github.com/nst/iOS-Runtime-Headers/blob/master/Frameworks/UIKit.framework/UIStatusBarForegroundStyleAttributes.h)

The warnings you get are pretty scary. `PhotosUICore.framework` is system framework and if it has same class names as StylingKit (actually from Pixate days) like PXUIView and PXUIImageView. The fix will be to rename all the classes that collide with system framework. You can try with 1 class and see if it is still listed in warnings.

**Comment by iellis** [comment]
Fixing the file collisions with PhotosUICore solved it. I'm not sure exactly what was going on with the subclassing, but it looked like as I fixed the collisions, the subclasses used for the UIStatusBar and its contents were changing. Once I fixed all the collisions, all was good.

**Comment by anton-matosov** [comment]
Nice!
I have found this https://github.com/JaviSoto/iOS10-Runtime-Headers/tree/master/PrivateFrameworks/PhotosUICore.framework and it proves that iOS introduced ton of classes that have overlap with Pixate names.
Can you please create PR with name collision fixes?

**Comment by iellis** [comment]
I can do that. For my local fix, I named the files/classes SKPX_.h /
SKPX_.m. Does that seem reasonable or do you have another suggestion?

**Comment by anton-matosov** [comment]
I use STK prefix for StylingKit classes
I want to get rid of PX prefix entirely as iOS widely use it and I don't want to clash with it again

**Comment by stijnvanderlaan** [comment]
Any update on this?

**Comment by anton-matosov** [comment]
I have never got a PR for the change and don't have enough time to fix it myself right now.

**Comment by anton-matosov** [comment]
If your app doesn't use `PhotosUICore.framework` there is no problem at all. Neither of my apps use it, so its not a blocker.
