### ISSUE TITLE
architecture i386 not supported.

### ISSUE THREAD

**Issue by kunal30xi** [StylingKit/StylingKit#52]
The import of StylingKit through Carthage now works great. Thank you for the quick turnaround on that.

I ran into the following error when attempting to run our test suite against code built with StylingKit:
`StylingKit.framework/StylingKit, file was built for x86_64 which is not the architecture being linked (i386):` 

Attempting to set BUILD_ACTIVE_ARCHITECTURES=NO on the targets within the workspace appears to resolve the issue. 

I'm happy to submit a PR with the change if it will be acceptable.

**Comment by anton-matosov** [comment]
Thanks for the PR
