### ISSUE TITLE
Skipped building StylingKit due to the error

### ISSUE THREAD

**Issue by marianaMarshaL** [StylingKit/StylingKit#55]
Hi I got this error "Dependency "StylingKit" has no shared framework schemes" everytime trying to install StylingKit using Carthage.
my Carthage version 0.17.2
xcode Version 7.3.1

is there anything i miss? please advise

**Comment by anton-matosov** [comment]
It looks like a duplicate of https://github.com/StylingKit/StylingKit/issues/48
Please make sure that you point to the latest develop revision

**Comment by marianaMarshaL** [comment]
I try to carthage update but it's still returning an error:

carthage update
**\* Fetching StylingKit
**\* Fetching CocoaLumberjack
**\* Checking out CocoaLumberjack at "2.3.0"
**\* Checking out StylingKit at "0.4.0"
**\* xcodebuild output can be found in /var/folders/bw/tk59hqmn06qcvzy5dbv64jgh0000gn/T/carthage-xcodebuild.Nwz4tH.log
**\* Building scheme "CocoaLumberjackSwift-tvOS" in Lumberjack.xcworkspace
**\* Skipped building StylingKit due to the error:
Dependency "StylingKit" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/StylingKit/StylingKit/issues/new
**\* Building scheme "CocoaLumberjackSwift" in Lumberjack.xcworkspace

**Comment by anton-matosov** [comment]
Issue was fixed in 0.4.1

**Comment by marianaMarshaL** [comment]
I just put this in Cartfile github "StylingKit/StylingKit" what should i add so i can get the updated?

**Comment by stupergenius** [comment]
@anton-matosov As @marianaMarshaL notes, there is currently no tagged release for `0.4.1` (the latest being `0.4.0`). If you could just tag the repo at the appropriate commit, it would resolve this issue.

**Comment by anton-matosov** [comment]
I have not tagged 0.4.1 because build start failing on travis and I didn't have time to fix it.
I will try to figure out the build issue and finally release 0.4.1

**Comment by anton-matosov** [comment]
Fixed in  https://github.com/StylingKit/StylingKit/pull/61
I have finally solved all the build issues with latest xcode and other deps and published 0.4.2 build (with 0.4.2 tag)
Please take it for a spin and let me know if you have any issues.
