### ISSUE TITLE
StylingKit Incompatible with MGBox2

### ISSUE THREAD

**Issue by infusixllc** [StylingKit/StylingKit#56]
This took me for_ever_ to figure out but StylingKit is incompatible with MGBox2.  When the podfile looks like this:

pod 'CocoaLumberjack', :git => "https://github.com/anton-matosov/CocoaLumberjack.git", :branch => "master"
pod 'StylingKit', :git => "https://github.com/StylingKit/StylingKit"
pod 'MGBox2'

Then StylingKit will work but hex values for colors will not work.  For instance:

.myclass { background-color: linear-gradient(red, yellow) } will work while
.myclass { background-color: linear-gradient(#ff0000, #00ff00) } will not work.  I don't know yet why this is the case but at least I found the conflict finally!

**Comment by infusixllc** [comment]
The trick for me at least was to change from MGBox2 to MGBoxKit.  MGBox2 has not been updated for 4 years.  But there is definitely some kind of incompatibility there.

**Comment by anton-matosov** [comment]
Closing the issue due to inactivity.
If issue still exists please feel free to provide more information and reopen or create new ticket.
